### ISSUE TITLE
doesn't generate the output video

### ISSUE THREAD

**Issue by pietrondo** [DanNixon/BubbleScopeCL#11] opened 2015-10-21 21:49 UTC
I have tried different times, but there is no output video...
could you help me?

**Comment by DanNixon** [comment] 2015-10-21 22:11
See #3.

Videos have been broken for a while thanks to OpenCV. Although I keep meaning to have another look at this.

**Comment by pietrondo** [comment] 2015-10-21 23:10
thx. because i can generate img

**Comment by DanNixon** [comment] 2015-11-23 12:30
Duplicate of #3

**Closed as completed by DanNixon** 2015-11-23 12:30 UTC
Labels: bug
